server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: payment_routh #路由ID，没有固定的规则，但要求唯一，建议配合服务名
         # uri: http://localhost:8001   #匹配后提供服务无的路由地址
          uri: lb://cloud-payment-service  #匹配后服务提供者的路由地址
          predicates:
            - Path=/payment/get/**  #

        - id: payment_routh2 #路由ID，没有固定的规则，但要求唯一，建议配合服务名
         # uri: http://localhost:8001   #匹配后提供服务无的路由地址
          uri: lb://cloud-payment-service  #匹配后服务提供者的路由地址
          predicates:
            - Path=/payment/lb/**  #
            - Query=gree, 1 #存在参数，名为green，值为1 注意是中文逗号
            #- Cookie=chocolate, ch.p
            #- Header=X-Request-Id,\d+ #
            #- Host=www.**.com #  输入www.com也可以成立
            #- Cookie=chocolate, ch.p

        - id: payment_routh3 #路由ID，没有固定的规则，但要求唯一，建议配合服务名
          uri: http://news.baidu.com/guonei   #匹配后提供服务无的路由地址，最终访问目的地
          predicates:
            - Path=/guonei # 映射ID
            # - After=2020-07-29T12:24:20.327+08:00[Asia/Shanghai] #表示在这个时间以后才能生效
            - Cookie=username, yymm #表示username为yymm才能生效
          #  - Header=X-Request-Id,\d+ #
          #  - Method=GET


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka

