server:
  port: 3344
spring:
  application:
    name: cloud-config-center # 注册进入微服务的名称
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liubaolai/springcloud-config.git
          search-paths:
            - springcloud-config
          force-pull: true
          username: liubaolai
          password: 4e009fa5
      label: master
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
